name: upmind_front_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  cookie_jar: ^4.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  drift: ^2.20.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  fgen: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.4.1
  flutter_kinescope_sdk: ^0.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  phone_form_field: ^9.2.7
  shared_preferences: ^2.3.2
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.4.6
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/core/utils/gen/

  lineLength: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/app_bar/
    - assets/icons/bottom_nav_bar/
    - assets/icons/common/
    - assets/images/
    - assets/logo/
    - lib/core/network/fixtures/main_screen_products.json
    - lib/core/network/fixtures/user_products.json
    - lib/core/network/fixtures/areas.json
    - lib/core/network/fixtures/user_notifications.json

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
